services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: dummykey1234567890
    volumes:
      - .:/rails
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
